# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 11:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import match.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('cohortId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cohortSize', models.IntegerField(default=0)),
                ('openDate', models.DateTimeField(default=datetime.datetime.now)),
                ('closeDate', models.DateTimeField(default=match.models._get_default_close_date)),
                ('matchDate', models.DateTimeField(default=match.models._get_default_match_date)),
            ],
        ),
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MentorshipScore',
            fields=[
                ('mentorshipScoreId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dateSent', models.DateTimeField(default=datetime.datetime.now)),
                ('received', models.BooleanField(default=False)),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='match.Mentorship')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participantId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('signUpDate', models.DateTimeField(default=datetime.datetime.now)),
                ('isMentor', models.BooleanField(default=False)),
                ('isMatched', models.BooleanField(default=False)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='match.Cohort')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('programmeId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to=match.models._get_image_path)),
                ('bannerImage', models.ImageField(blank=True, null=True, upload_to=match.models._get_image_path)),
                ('defaultCohortSize', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('updateId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updateType', models.CharField(max_length=10)),
                ('title', models.TextField()),
                ('message', models.TextField()),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='match.Mentorship')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joinDate', models.DateTimeField(default=datetime.datetime.now)),
                ('position', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('dateOfBirth', models.DateTimeField()),
                ('bio', models.TextField()),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to=match.models._get_image_path)),
                ('tags', models.ManyToManyField(related_name='UserTag', to='match.Tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='programme',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='match.UserProfile'),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to='match.Participant'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to='match.Participant'),
        ),
        migrations.AddField(
            model_name='mentorshipscore',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='match.Participant'),
        ),
        migrations.AddField(
            model_name='mentorshipscore',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='match.Participant'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_mentorships', to='match.Participant'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_mentorships', to='match.Participant'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='match.UserProfile'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='match.Programme'),
        ),
    ]
