# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 16:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
import match.validators.user_validators


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_auto_20170213_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='openDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='dateSent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='participant',
            name='signUpDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True, validators=[match.validators.user_validators.validate_joinDate]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='joinDate',
            field=models.DateField(default=datetime.datetime.today, null=True, validators=[match.validators.user_validators.validate_joinDate]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
