# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 16:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import match.validators.user_validators


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_auto_20170217_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='joinDate',
            field=models.DateField(default=datetime.date.today, null=True, validators=[match.validators.user_validators.validate_joinDate]),
        ),
    ]
