# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 17:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_auto_20170219_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='programme',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to=settings.AUTH_USER_MODEL),
        ),
    ]
