# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_auto_20170308_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='tags',
            field=models.ManyToManyField(related_name='ParticipantTag', to='match.Tag'),
        ),
    ]
