# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 23:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('match', '0009_auto_20170321_2042'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set([('user', 'cohort')]),
        ),
    ]
