# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0010_auto_20170322_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.CharField(default='', max_length=30),
        ),
    ]
