# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0011_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='isTopThreeSelected',
            field=models.BooleanField(default=False),
        ),
    ]
